server:
  port: 8761
eureka:
  instance:
    hostname: server1
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://pangbohuan:pbh.3644@127.0.0.1:8762/eureka,http://pangbohuan:pbh.3644@127.0.0.1:8763/eureka